sudo: false
language: python
python:
  - 2.7
addons:
  postgresql: 9.4
env:
  global:
    - INDICO_CONFIG=/dev/null
install:
  - pip install -U pip setuptools
  - pip install -r requirements.txt
  - python setup.py develop
script:
  - pytest -v
notifications:
  email: false
  irc:
    channels:
      - 'chat.freenode.net#indico'
    use_notice: true
    skip_join: true
