language: python
python:
  - "2.7"
env:
  - TEST_SUITE=unit
  - TEST_SUITE=functional
before_install:
  - '[[ "$TEST_SUITE" == "functional" ]] && export DISPLAY=:99.0 || :'
  - '[[ "$TEST_SUITE" == "functional" ]] && /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16 || :'
install:
  - pip install -U setuptools
  - pip install suds-jurko
  - python setup.py develop
  - '[[ "$TEST_SUITE" == "functional" ]] && fab setup_deps:system_node=1 || :'
script:
  - python setup.py test --$TEST_SUITE --clean-shutdown
notifications:
  email: false
  irc:
    channels:
      - 'chat.freenode.net#indico'
    use_notice: true
    skip_join: true
